folders:
  - folder_name: "Deliver"
    folder_desc: "Deliver folder"
jobs:
  - job_name: "PushToProd"
    job_description: "This is my awesome Job"
    git_url: "ssh://git@localhost:7999/test/test.git"
    creds_id: "bb"
    branch: "master"
    script_path: "Jenkinsfile"
    folder: "Deliver"
    parameters:
      - name: "param2"
        value: |
          {
            "holi": "holi"
          }
        desc: "This is the ea"
        type: textParam

  - job_name: "PushToStg"
    job_description: "This is my awesome Job2"
    git_url: "ssh://git@localhost:7999/test/test.git"
    creds_id: "bb"
    branch: "master"
    script_path: "Jenkinsfile2"
    folder: "Deliver"
    parameters:
    - name: "qw2"
      value: "2"
      desc: "2"
      type: stringParam
    - name: "2"
      value: "2"
      desc: "2 is the ea"
      type: textParam